contatos_destino = [
    "11 M 20b Arapongas",
    "2 H 20 Loja Mimo Moda Infantil",
    "6 H 26 Arapongas",
    "Ab",
    "Adão Cliente",
    "Adriana 25 A 15",
    "Adriana Cliente",
    "Adriana Cliente",
    "Adriane Cliente",
    "Adriano",
    "Adryan Piaiu",
    "Agro Carreiro Buritis",
    "Agro Carreiro J Roriz",
    "Ailton 2 2F  47 Roriz",
    "Airton 23 F 21",
    "Alanah 31 DP",
    "Alessandra Caesb",
    "Alessandra Caroline",
    "Alessandra Cliente",
    "Alessandra Fórum",
    "ALESSANDRA VILA DE FATIMA",
    "Alessandro",
    "Alex Av Marechal Q 89 lote 20 setor sul",
    "Alex Cliente",
    "Alexandre",
    "Alexandre Piaui",
    "Alice 22 G 26",
    "Aline Rua Bernardo Sayão 158 1A Boteco Do Bigode",
    "Alisson",
    "Aluizio",
    "Amado",
    "Amanda CEF 03",
    "Amanda Grazielle",
    "Amanda Soares",
    "Amiga Do Laércio",
    "Amigo Do Pedro Paulo",
    "Ana 18 F 20",
    "Ana 2a A 21 Arapoanga",
    "Ana Carolina 3 B 3 Buritis",
    "Ana Clara",
    "Ana Dutra",
    "Ana Maria 02 G 37 Buritis",
    "Anderson Cliente",
    "Andréa Ana Cliente",
    "Andreia",
    "Andreia",
    "Andreia 21 J 4",
    "andreia ATriagem Ps Hospital",
    "Andreia Cliente",
    "Andressa 04E  C 09 Arapoanga",
    "Andressa Costa Cliente",
    "Anne Gabriela",
    "Antônia",
    "Antonia 14. 5. 7 B3",
    "Antônia Andrade",
    "Ao",
    "Ap",
    "Aparecida",
    "Aparecida 24 L 13",
    "Aq",
    "Ar",
    "Arlene",
    "Armarinho Medeiros Bianca",
    "Arnaldo Cliente",
    "Arthur Cardoso",
    "Arthur Q2 Casa 17 Vila Vicentina",
    "Au",
    "Av",
    "Av Independência 65 15",
    "Av São Paulo 85 16 Apto 205",
    "Aw",
    "Ax",
    "Ay",
    "Az",
    "B",
    "B",
    "Batata",
    "Batista",
    "Bella 19 B 27",
    "Bergson Piauí 26 D 22 Portão Pequeno",
    "Bete Félix",
    "Beto Novais",
    "Bia",
    "Bia Cliente",
    "Bispa Flávia",
    "Brenda 05 G 21",
    "Brendon Piauí",
    "Breno Araujo",
    "Bruna 25 A 10",
    "Bruna Soares",
    "Bruno",
    "Bruno Agropecuária Pet Agro Arapoanga",
    "Bruno L",
    "Bruno Policial",
    "C",
    "Caetano Cliente",
    "Caio Lucas",
    "Camila",
    "Camila Cliente",
    "Camila Lago Malta",
    "Camila Lima",
    "Carla 05b B 29 Arapoanga Abel Dias Advocacia",
    "Carla Instituto Maria Do Barro",
    "Carla Patrícia",
    "Carlos André",
    "Carlos Braga",
    "CARLOS Cliente",
    "Caroline 01 J 31 Arapongas",
    "Caroline Sa",
    "Cassia Cliente",
    "Cassio troca de óleo",
    "Celso",
    "Cesar 24 F 02",
    "Cesar 5 A 40 Tc Biju",
    "Chacara 08 Córrego Do Atoleiro",
    "Chagas",
    "Cicero 19 K Área Especial Do B4",
    "Cida Lopes",
    "Cíntia 18 i 15A Arapoanga",
    "Cirlene",
    "Cirlene",
    "Claudete 23 F 22",
    "Cláudia Gonçalves 18 C 03",
    "claudio",
    "Claudionor Cliente",
    "Cleber 1 1b 48 Roriz",
    "Cleber Barbearia Do Gaúcho",
    "Cleber Cliente",
    "Cleber Cliente",
    "Cleber Cliente",
    "Cleia",
    "Clenio",
    "Cliente",
    "Cliente",
    "Cliente",
    "Cliente 0000",
    "Cliente 00008",
    "Cliente 0001",
    "Cliente 0002",
    "Cliente 0003",
    "Cliente 0004",
    "Cliente 0005",
    "Cliente 0006",
    "Cliente 0007",
    "Cliente 0009",
    "Cliente 003",
    "Cliente 004",
    "Cliente 005",
    "Cliente 005",
    "Cliente 006",
    "Cliente 006",
    "Cliente 006",
    "Cliente 007",
    "Cliente 009",
    "Cliente 01 H 13 Roriz",
    "Cliente 010",
    "Cliente 011",
    "Cliente 012",
    "Cliente 013",
    "Cliente 014",
    "Cliente 015",
    "Cliente 016",
    "Cliente 017",
    "Cliente 018",
    "Cliente 02",
    "Cliente 020",
    "Cliente 021",
    "Cliente 022",
    "Cliente 023",
    "Cliente 024",
    "Cliente 025",
    "Cliente 026",
    "Cliente 027",
    "Cliente 028",
    "Cliente 029",
    "Cliente 03 B 6 Frente Pro A",
    "Cliente 03 D 48 Roriz Colher",
    "Cliente 030",
    "Cliente 031",
    "Cliente 032",
    "Cliente 033",
    "Cliente 034",
    "Cliente 035",
    "Cliente 036",
    "Cliente 037",
    "Cliente 038",
    "Cliente 039",
    "Cliente 040",
    "Cliente 041",
    "Cliente 042",
    "Cliente 043",
    "Cliente 044",
    "Cliente 045",
    "Cliente 046",
    "Cliente 047",
    "Cliente 048",
    "Cliente 049",
    "Cliente 04B B 34 Arapongas",
    "Cliente 050",
    "Cliente 051",
    "Cliente 053",
    "Cliente 054",
    "Cliente 055",
    "Cliente 056",
    "Cliente 057",
    "Cliente 058",
    "Cliente 059",
    "Cliente 060",
    "Cliente 061",
    "Cliente 062",
    "Cliente 063",
    "Cliente 064",
    "Cliente 065",
    "Cliente 066",
    "Cliente 069",
    "Cliente 070",
    "Cliente 071",
    "Cliente 072",
    "Cliente 073",
    "Cliente 074",
    "Cliente 076",
    "Cliente 077",
    "Cliente 078",
    "Cliente 079",
    "Cliente 080",
    "Cliente 081",
    "Cliente 083",
    "Cliente 084",
    "Cliente 085",
    "Cliente 086",
    "Cliente 087",
    "Cliente 089",
    "Cliente 090",
    "Cliente 091",
    "Cliente 093",
    "Cliente 095",
    "Cliente 096",
    "Cliente 1000",
    "Cliente 101",
    "Cliente 102",
    "Cliente 103",
    "Cliente 104",
    "Cliente 106",
    "Cliente 108",
    "Cliente 109",
    "Cliente 111",
    "Cliente 113",
    "Cliente 114",
    "Cliente 115",
    "Cliente 116",
    "Cliente 117",
    "Cliente 118",
    "Cliente 119",
    "Cliente 120",
    "Cliente 121",
    "Cliente 122",
    "Cliente 123",
    "Cliente 124",
    "Cliente 125",
    "Cliente 126",
    "Cliente 127",
    "Cliente 128",
    "Cliente 129",
    "Cliente 130",
    "Cliente 131",
    "Cliente 132",
    "Cliente 133",
    "Cliente 134",
    "Cliente 135",
    "Cliente 136",
    "Cliente 137",
    "Cliente 138",
    "Cliente 139",
    "Cliente 140",
    "Cliente 141",
    "Cliente 142",
    "Cliente 143",
    "Cliente 144",
    "Cliente 146",
    "Cliente 147",
    "Cliente 148",
    "Cliente 149",
    "Cliente 150",
    "Cliente 151",
    "Cliente 152",
    "Cliente 153",
    "Cliente 154",
    "Cliente 155",
    "Cliente 156",
    "Cliente 157",
    "Cliente 158",
    "Cliente 159",
    "Cliente 160",
    "Cliente 161",
    "Cliente 162",
    "Cliente 163",
    "Cliente 164",
    "Cliente 165",
    "Cliente 166",
    "Cliente 167",
    "Cliente 168",
    "Cliente 169",
    "Cliente 170",
    "Cliente 171",
    "Cliente 172",
    "Cliente 173",
    "Cliente 174",
    "Cliente 175",
    "Cliente 176",
    "Cliente 177",
    "Cliente 178",
    "Cliente 179",
    "Cliente 180",
    "Cliente 181",
    "Cliente 182",
    "Cliente 183",
    "Cliente 184",
    "Cliente 185",
    "Cliente 186",
    "Cliente 187",
    "Cliente 188",
    "Cliente 189",
    "Cliente 190",
    "Cliente 191",
    "Cliente 192",
    "Cliente 193",
    "Cliente 194",
    "Cliente 195",
    "Cliente 196",
    "Cliente 197",
    "Cliente 198",
    "Cliente 199",
    "Cliente 200",
    "Cliente 201",
    "Cliente 202",
    "Cliente 203",
    "Cliente 204",
    "Cliente 205",
    "Cliente 206",
    "Cliente 207",
    "Cliente 208",
    "Cliente 209",
    "Cliente 21 Buritis 4",
    "Cliente 21 i 01",
    "Cliente 210",
    "Cliente 211",
    "Cliente 212",
    "Cliente 213",
    "Cliente 214",
    "Cliente 215",
    "Cliente 216",
    "Cliente 217",
    "Cliente 218",
    "Cliente 219",
    "Cliente 220",
    "Cliente 221",
    "Cliente 222",
    "Cliente 223",
    "Cliente 224",
    "Cliente 225",
    "Cliente 226",
    "Cliente 227",
    "Cliente 228",
    "Cliente 229",
    "Cliente 230",
    "Cliente 231",
    "Cliente 232",
    "Cliente 233",
    "Cliente 234",
    "Cliente 235",
    "Cliente 236",
    "Cliente 237",
    "Cliente 238",
    "Cliente 239",
    "Cliente 240",
    "Cliente 241",
    "Cliente 242",
    "Cliente 243",
    "Cliente 244",
    "Cliente 245",
    "Cliente 246",
    "Cliente 247",
    "Cliente 248",
    "Cliente 249",
    "Cliente 250",
    "Cliente 251",
    "Cliente 252",
    "Cliente 253",
    "Cliente 254",
    "Cliente 255",
    "Cliente 256",
    "Cliente 257",
    "Cliente 258",
    "Cliente 259",
    "Cliente 260",
    "Cliente 261",
    "Cliente 262",
    "Cliente 263",
    "Cliente 264",
    "Cliente 265",
    "Cliente 266",
    "Cliente 267",
    "Cliente 268",
    "Cliente 269",
    "Cliente 270",
    "Cliente 272",
    "Cliente 273",
    "Cliente 274",
    "Cliente 275",
    "Cliente 276",
    "Cliente 277",
    "Cliente 278",
    "Cliente 279",
    "Cliente 280",
    "Cliente 281",
    "Cliente 282",
    "Cliente 283",
    "Cliente 284",
    "Cliente 285",
    "Cliente 286",
    "Cliente 287",
    "Cliente 288",
    "Cliente 289",
    "Cliente 290",
    "Cliente 291",
    "Cliente 292",
    "Cliente 293",
    "Cliente 294",
    "Cliente 295",
    "Cliente 296",
    "Cliente 297",
    "Cliente 298",
    "Cliente 299",
    "Cliente 300",
    "Cliente 301",
    "Cliente 302",
    "Cliente 303",
    "Cliente 304",
    "Cliente 305",
    "Cliente 306",
    "Cliente 307",
    "Cliente 308",
    "Cliente 309",
    "Cliente 310",
    "Cliente 311",
    "Cliente 312",
    "Cliente 313",
    "Cliente 314",
    "Cliente 316",
    "Cliente 317",
    "Cliente 318",
    "Cliente 319",
    "Cliente 320",
    "Cliente 321",
    "Cliente 322",
    "Cliente 323",
    "Cliente 324",
    "Cliente 325",
    "Cliente 326",
    "Cliente 328",
    "Cliente 329",
    "Cliente 330",
    "Cliente 331",
    "Cliente 332",
    "Cliente 333",
    "Cliente 334",
    "Cliente 335",
    "Cliente 336",
    "Cliente 337",
    "Cliente 338",
    "Cliente 339",
    "Cliente 340",
    "Cliente 341",
    "Cliente 342",
    "Cliente 343",
    "Cliente 344",
    "Cliente 345",
    "Cliente 346",
    "Cliente 347",
    "Cliente 348",
    "Cliente 349",
    "Cliente 350",
    "Cliente 351",
    "Cliente 352",
    "Cliente 353",
    "Cliente 354",
    "Cliente 355",
    "Cliente 356",
    "Cliente 357",
    "Cliente 358",
    "Cliente 359",
    "Cliente 360",
    "Cliente 361",
    "Cliente 362",
    "Cliente 363",
    "Cliente 364",
    "Cliente 365",
    "Cliente 366",
    "Cliente 367",
    "Cliente 368",
    "Cliente 369",
    "Cliente 370",
    "Cliente 371",
    "Cliente 372",
    "Cliente 373",
    "Cliente 374",
    "Cliente 375",
    "Cliente 376",
    "Cliente 377",
    "Cliente 378",
    "Cliente 379",
    "Cliente 380",
    "Cliente 381",
    "Cliente 382",
    "Cliente 383",
    "Cliente 384",
    "Cliente 385",
    "Cliente 386",
    "Cliente 387",
    "Cliente 388",
    "Cliente 389",
    "Cliente 390",
    "Cliente 391",
    "Cliente 392",
    "Cliente 393",
    "Cliente 394",
    "Cliente 395",
    "Cliente 396",
    "Cliente 397",
    "Cliente 398",
    "Cliente 399",
    "Cliente 400",
    "Cliente 401",
    "Cliente 402",
    "Cliente 403",
    "Cliente 404",
    "Cliente 405",
    "Cliente 406",
    "Cliente 407",
    "Cliente 408",
    "Cliente 409",
    "Cliente 410",
    "Cliente 411",
    "Cliente 412",
    "Cliente 413",
    "Cliente 414",
    "Cliente 415",
    "Cliente 416",
    "Cliente 417",
    "Cliente 418",
    "Cliente 419",
    "Cliente 420",
    "Cliente 421",
    "Cliente 422",
    "Cliente 423",
    "Cliente 424",
    "Cliente 425",
    "Cliente 426",
    "Cliente 427",
    "Cliente 428",
    "Cliente 429",
    "Cliente 430",
    "Cliente 431",
    "Cliente 432",
    "Cliente 433",
    "Cliente 434",
    "Cliente 435",
    "Cliente 436",
    "Cliente 437",
    "Cliente 438",
    "Cliente 439",
    "Cliente 440",
    "Cliente 441",
    "Cliente 442",
    "Cliente 443",
    "Cliente 445",
    "Cliente 446",
    "Cliente 447",
    "Cliente 448",
    "Cliente 449",
    "Cliente 450",
    "Cliente 451",
    "Cliente 452",
    "Cliente 453",
    "Cliente 454",
    "Cliente 455",
    "Cliente 456",
    "Cliente 457",
    "Cliente 458",
    "Cliente 459",
    "Cliente 460",
    "Cliente 461",
    "Cliente 462",
    "Cliente 463",
    "Cliente 464",
    "Cliente 465",
    "Cliente 466",
    "Cliente 467",
    "Cliente 468",
    "Cliente 469",
    "Cliente 470",
    "Cliente 471",
    "Cliente 472",
    "Cliente 473",
    "Cliente 474",
    "Cliente 475",
    "Cliente 476",
    "Cliente 477",
    "Cliente 478",
    "Cliente 479",
    "Cliente 480",
    "Cliente 481",
    "Cliente 482",
    "Cliente 483",
    "Cliente 484",
    "Cliente 485",
    "Cliente 486",
    "Cliente 487",
    "Cliente 488",
    "Cliente 489",
    "Cliente 490",
    "Cliente 491",
    "Cliente 494",
    "Cliente 495",
    "Cliente 496",
    "Cliente 497",
    "Cliente 498",
    "Cliente 499",
    "Cliente 500",
    "Cliente 501",
    "Cliente 502",
    "Cliente 503",
    "Cliente 504",
    "Cliente 505",
    "Cliente 506",
    "Cliente 507",
    "Cliente 508",
    "Cliente 509",
    "Cliente 510",
    "Cliente 511",
    "Cliente 512",
    "Cliente 513",
    "Cliente 514",
    "Cliente 515",
    "Cliente 516",
    "Cliente 517",
    "Cliente 518",
    "Cliente 519",
    "Cliente 520",
    "Cliente 521",
    "Cliente 522",
    "Cliente 523",
    "Cliente 524",
    "Cliente 525",
    "Cliente 526",
    "Cliente 527",
    "Cliente 528",
    "Cliente 529",
    "Cliente 530",
    "Cliente 531",
    "Cliente 532",
    "Cliente 533",
    "Cliente 534",
    "Cliente 535",
    "Cliente 536",
    "Cliente 537",
    "Cliente 538",
    "Cliente 539",
    "Cliente 540",
    "Cliente 541",
    "Cliente 542",
    "Cliente 543",
    "Cliente 544",
    "Cliente 545",
    "Cliente 546",
    "Cliente 547",
    "Cliente 548",
    "Cliente 549",
    "Cliente 550",
    "Cliente 551",
    "Cliente 551",
    "Cliente 552",
    "Cliente 553",
    "Cliente 554",
    "Cliente 555",
    "Cliente 556",
    "Cliente 557",
    "Cliente 558",
    "Cliente 559",
    "Cliente 560",
    "Cliente 600",
    "Cliente 602",
    "Cliente 603",
    "Cliente 604",
    "Cliente 606",
    "Cliente 607",
    "Cliente 608",
    "Cliente 609",
    "Cliente 610",
    "Cliente 611",
    "Cliente 612",
    "Cliente 613",
    "Cliente 614",
    "Cliente 615",
    "Cliente 616",
    "Cliente 617",
    "Cliente 618",
    "Cliente 619",
    "Cliente 621",
    "Cliente 622",
    "Cliente 623",
    "Cliente 624",
    "Cliente 625",
    "Cliente 626",
    "Cliente 627",
    "Cliente 628",
    "Cliente 629",
    "Cliente 630",
    "Cliente 631",
    "Cliente 632",
    "Cliente 633",
    "Cliente 634",
    "Cliente 635",
    "Cliente 636",
    "Cliente 637",
    "Cliente 638",
    "Cliente 639",
    "Cliente 640",
    "Cliente 641",
    "Cliente 642",
    "Cliente 643",
    "Cliente 644",
    "Cliente 645",
    "Cliente 646",
    "Cliente 647",
    "Cliente 648",
    "Cliente 649",
    "Cliente 650",
    "Cliente 651",
    "Cliente 652",
    "Cliente 653",
    "Cliente 654",
    "Cliente 655",
    "Cliente 656",
    "Cliente 657",
    "Cliente 658",
    "Cliente 659",
    "Cliente 660",
    "Cliente 661",
    "Cliente 662",
    "Cliente 663",
    "Cliente 664",
    "Cliente 665",
    "Cliente 666",
    "Cliente 666",
    "Cliente 667",
    "Cliente 667",
    "Cliente 668",
    "Cliente 668",
    "Cliente 669",
    "Cliente 670",
    "Cliente 671",
    "Cliente 672",
    "Cliente 673",
    "Cliente 674",
    "Cliente 675",
    "Cliente 676",
    "Cliente 677",
    "Cliente 678",
    "Cliente 679",
    "Cliente 680",
    "Cliente 681",
    "Cliente 682",
    "Cliente 683",
    "Cliente 684",
    "Cliente 685",
    "Cliente 686",
    "Cliente 687",
    "Cliente 688",
    "Cliente 689",
    "Cliente 690",
    "Cliente 691",
    "Cliente 692",
    "Cliente 693",
    "Cliente 694",
    "Cliente 695",
    "Cliente 696",
    "Cliente 697",
    "Cliente 698",
    "Cliente 699",
    "Cliente 700",
    "Cliente 701",
    "Cliente 702",
    "Cliente 703",
    "Cliente 704",
    "Cliente 705",
    "Cliente 706",
    "Cliente 707",
    "Cliente 708",
    "Cliente 709",
    "Cliente 710",
    "Cliente 711",
    "Cliente 713",
    "Cliente 714",
    "Cliente 715",
    "Cliente 716",
    "Cliente 717",
    "Cliente 718",
    "Cliente 719",
    "Cliente 720",
    "Cliente 721",
    "Cliente 722",
    "Cliente 723",
    "Cliente 724",
    "Cliente 725",
    "Cliente 726",
    "Cliente 727",
    "Cliente 728",
    "Cliente 729",
    "Cliente 730",
    "Cliente 731",
    "Cliente 732",
    "Cliente 733",
    "Cliente 734",
    "Cliente 735",
    "Cliente 736",
    "Cliente 738",
    "Cliente 739",
    "Cliente 740",
    "Cliente 741",
    "Cliente 742",
    "Cliente 745",
    "Cliente 749",
    "Cliente 750",
    "Cliente 751",
    "Cliente 755",
    "Cliente 760",
    "Cliente 761",
    "Cliente 780",
    "Cliente 782",
    "Cliente 783",
    "Cliente 788",
    "Cliente Buritis 4",
    "Cliente Do Salão",
    "Cliente Ginasio Do B3",
    "Cliente Horta",
    "Cliente Jonathan",
    "Cliente Laila Cdc",
    "Cliente Paulo",
    "Cliente Sagora",
    "Cliente Sem Endereço",
    "Cliente Soft",
    "Cliente Vila Dimas",
    "Conceição Cliente",
    "Cris Cardoso Cliente",
    "Cris Da OAB Fórum",
    "Cris Sales",
    "Crislayne Cliente",
    "Cristiana 3 D 54 Fundos",
    "Cristiane 19 C 21",
    "Cristiane 24 H 12",
    "Cristiano Alves",
    "Cyntia Cliente",
    "Daiana 24 H 10",
    "Daiane Lins",
    "Dani Horta Rua B Chácara 22",
    "Daniel 1 E 46 Roriz",
    "Daniel Centrão",
    "Daniel Cliente",
    "Daniel Inspetoria",
    "Daniel Motoboy",
    "Daniela Caic",
    "Danilo Drogaria B3",
    "Débora 3 F 8",
    "Deivid",
    "Delegado Bruno",
    "Demerlice 12 F 13A Arapoanga",
    "Deneir",
    "Denilson Bernardo Sayão 158  1A",
    "Denise Morena iluminada ❤️",
    "Denise Oliveira Cliente",
    "Deus é Fiel",
    "Diego 19 K Área Especial 1",
    "Diego Cristino Pronto Clínica",
    "Diego Elétrica Car",
    "Diego Gerente",
    "DIGITAL ELETRON",
    "Dinha Cliente",
    "Diogenes Da Conceição Cou",
    "Domezil 3 3J 31 Roriz",
    "Dona Francisca",
    "Dora Goncalves Cliente",
    "Dorival Cliente",
    "Douglas Motoboy",
    "Dra Geane Carneiro",
    "E",
    "E",
    "E E2",
    "Éder",
    "Eder 02 G 34",
    "Eder B3",
    "𝑬𝒅𝒈𝒂𝒓 Cliente",
    "Edicleide",
    "Edilene",
    "Edilson Cliente",
    "Edinaldo Av Maranhao",
    "Edinaldo Cliente Obra",
    "Edinéia 3 3b 40 Roriz",
    "Edlaine Souza",
    "Edna Alves",
    "Edna Cliente",
    "Edna Cliente",
    "Edson Cliente",
    "Eduarda 22 G 4",
    "Eduardo",
    "Eduardo",
    "Eduardo 11 i 1d Arapoanga",
    "Eduardo Cliente",
    "Eduardo Motoboy",
    "Ee",
    "Elaine 21 D 12 B4",
    "Eldiene",
    "Elen",
    "Eliane",
    "Elita Cliente",
    "Emanuelle Gomes",
    "Embala Brasil",
    "Embalagem Lucena",
    "Emilly Suyara",
    "Emily 03 A 20 Salão Da Zeny",
    "Enfermeira Danielle Hospital",
    "Erica Cliente",
    "Erick 21 J 24",
    "Erika Itaú",
    "Ernando Cliente",
    "Escola Classe 06 Vigilante",
    "Esposo Aline Restaurante",
    "Euzanetpires",
    "Eva 20 I 01",
    "Eva Unic Fashion 20 I 01",
    "Evanio Cliente",
    "Evellyn",
    "Evellyn Cliente",
    "Everton Cesar",
    "Fabiano Motoboy",
    "Fabio",
    "Fábrica de pizza",
    "Fabrício Cliente",
    "Fátima",
    "Fátima Cliente",
    "Fc shoes",
    "Felipe 22A D 05 Marcenaria",
    "Felipe Edilene",
    "Fernanda",
    "Fernanda 7J D 10a Arapoanga",
    "Fernanda Dutra",
    "Fernanda Santos",
    "Fernando",
    "Fernando",
    "Fernando Cliente",
    "Fernando Cliente",
    "FERNANDO FARIAS",
    "Filipe",
    "Flavia Ferreira",
    "Flavia Rua 1 De Junho, 142. Cs 8 - FAISA",
    "Flávio Joias",
    "Fran Cliente",
    "Francisca 19 G 36",
    "Francisca Cliente",
    "Francisca Cliente 12",
    "Francisco",
    "Francisco Cliente",
    "Francisco clodoaldo",
    "Francisco Lino",
    "Francisco Xavier",
    "Francisco Xavier Xavier",
    "Gabriele Rocha",
    "Gabrielle 03 E 05 Buritis",
    "Gabryel Cliente",
    "Gaby Cliente",
    "Gedson Cliente",
    "Geisiane 24 G 14",
    "Geminiano 3 H 20 Elétrica Burifios",
    "Geneci Inácio",
    "Gigi 24 M 21",
    "Gildeane 24 L 28",
    "Giliana 18 B 25",
    "Gilman Igreja De Cristo Vida Nova",
    "Gilmar Cliente",
    "Gilson Fórum",
    "Gilvan",
    "Gilvania Cliente",
    "Giovani Cliente Like Internet",
    "Giovanna CEF 03",
    "Giovanna Gomes",
    "Girlene Cliente",
    "Giúlio Kelsin",
    "Glauciana 2 H 20",
    "Golpista",
    "Gomes",
    "Graça Córrego Do Atoleiro",
    "GRAZIELA REIS Q14,Cj 01,Cs16 B3",
    "Graziele 4 C 20 Loja B - Boutique Dos Orixás",
    "Guilherme Andrade",
    "Guilherme Cliente",
    "Guilherme Henrique",
    "H",
    "H",
    "Hélio",
    "Hellen 25 B 02",
    "Hercílio 3 I",
    "Herminio Junior",
    "Hev Maia Cliente",
    "Indihamara",
    "Ingrid 2 2j 11 Roriz",
    "Ingrid Cliente",
    "Iracema",
    "Isadora Mercado Andrade",
    "Isaque 24 M 02",
    "Israel Cliente",
    "Itallo 2a. A 30",
    "Itiquira Radiadores",
    "Ivan",
    "Ivan Carvalho Carvalho",
    "Ivone 25 A 04",
    "Ivonei Ismael",
    "Ivoneide C.Evangelista",
    "J",
    "J.Lenilson Lenilson",
    "Jailson Q13,4, Casa 01",
    "Janaína",
    "Jaque",
    "Jaqueline",
    "Jaqueline 20 E 26",
    "Javam 21 D 27",
    "Jayrynho Cliente",
    "JECIEL ARANTES",
    "Jeferson Policial Civil",
    "Jeferson Silva",
    "Jéssica 23 B 02",
    "Jéssica 25 A 23",
    "Jessica Cliente",
    "Jhonatan 4 A 41",
    "Joana 5 F 48 Roriz",
    "João 26 E 40",
    "João Paulo Motoboy",
    "João Pedro Raça Embalagens",
    "João Victor Cliente",
    "Joaquim",
    "Joaquim Ferreira",
    "Jocimar 22 A 24",
    "Johnny Óticas Carol",
    "Jonatas Mercado Paladares",
    "Jööh Instituto Maria Do Barro",
    "José Alexandre Cliente",
    "José Francisco",
    "José Laerte Cliente",
    "Josiane Cliente",
    "Josué Silva cliente",
    "Josy 05 D 42",
    "Josy Guimarães Líder Material De Construção",
    "Jota 4 D 27",
    "Jovem",
    "Jovem 20 I 31",
    "Joyce Cliente",
    "JRN BEEF CARNES",
    "Jucivana 21 G 27",
    "Juliana Ágata",
    "Juliana Nogueira",
    "Júlio Do Fórum",
    "Juninho",
    "Juracir Cliente",
    "Juracir Cliente",
    "kamila Esposa Mineiro",
    "Kamilly",
    "Kamilly Supermercado Nunes",
    "Karina",
    "Karine 11 I 1b",
    "Karine Cliente",
    "Kassia Vigilante Escola Classe 06",
    "Kátia 13. 08. 11 B3",
    "Kedma Kids Feira",
    "Keila",
    "Kellen Cliente",
    "Kellen Q11,Conj 3, Casa 02",
    "Ketlen 4 E 32 Roriz",
    "L",
    "Laércio",
    "Laercio Motoboy",
    "Lais Cliente",
    "Laryssa 2 D 20 Buritis",
    "Layane",
    "Lays Horta Comunitária",
    "Lays Loja Dimensão",
    "Láysa Chácara 14 Horta Comunitária",
    "Laysa Horta",
    "Leandro Piauí",
    "Leida Clínica Florence",
    "Leide",
    "Leila 22 A 46",
    "Lenira",
    "Leonardo Alves Cliente",
    "Leormindo 26 A 09",
    "Letícia Cliente",
    "Lidiane 06 F 02",
    "Lidiane Gomes Contabilidade",
    "Ligia 19 K Área Especial 01",
    "Lili",
    "Liliane Pereira",
    "Lilliá 3 B 23 - CORBAN",
    "Lina 23 F 10",
    "Lorena 02 K 02 Buritis",
    "Luan",
    "Luan 22A. G. 1",
    "Luan  5 E 40 Vila Buritis",
    "Luan Ferrero",
    "Luana Cliente",
    "Luanda Cliente",
    "Lucas",
    "Lucas 10 A 35 B3",
    "Lucas 21 B 21",
    "Lucas 24 D 25 B4",
    "Lucas Costa Vitória Embalagens Ao Lado Da Agropecuária",
    "Lucas liberal 31DP",
    "Lucas Martins",
    "Lucas Rua Para",
    "Lucelia 50 13 Apt 202",
    "Lucia",
    "Lucia IVONEI",
    "Luciana 08 H 14 Arapongas",
    "Luciene CEF 03- Sala De Recursos",
    "Lucilene 2 H Loja 01 Arapoanga",
    "Lucilia 2 B 22",
    "Lucimar",
    "Lucineide Cliente",
    "Ludimila Sup Andrade",
    "Luís Fernando",
    "Luiz Belota Fórum, Ramal 2402",
    "Luiz Cruz Cruz",
    "LUIZA Triagem Ps",
    "Lytha Cliente",
    "Lyvia Farma",
    "M",
    "Maciel 25 H 16",
    "Magda",
    "Magda",
    "Maicon 24 E 09",
    "Maicon Douglas Casa Do Adubo",
    "Maicon Raça Embalagens",
    "Máikon 3 H 41",
    "Maisa 22 A 40",
    "Maquininha de cartão Ton",
    "Marcelo",
    "Marcelo 25 F 10 Comando",
    "Marcelo Junior",
    "Márcia 12.05.03 B3",
    "Marcia Helena",
    "Marcos 01 i 40 Buritis",
    "Marcos 20 G 14",
    "Marcos Gomes",
    "Marcos Kodama Kodama",
    "Marcos Paulo",
    "Maressa farias",
    "Maria Cláudia 11 L 59 Arapoanga",
    "Maria de Lourdes Cliente",
    "Maria José 12 7 13",
    "Maria Margarida Rocca No Roriz",
    "Maria Sales 13 4 13 B3",
    "Mariana  22 K 36",
    "Mariana 26 G 07",
    "Mariana 31 DP",
    "Mariana Mercado Paladares 3",
    "Marina B",
    "Marlene Carreiro",
    "Marli",
    "Marlucia",
    "Marta 05 D 12 Casa 02 Buritis",
    "Mary Filha Do Seu Ceará 112",
    "Mary Ortholife Cliente",
    "Mateus Cliente",
    "Mateus S",
    "Matheus Dos Anjos Piaui",
    "Matheus Lima",
    "Matheus Oliveira",
    "Maura",
    "Maynne",
    "Michele",
    "Michele 10e B 25",
    "Michele 24 J 24",
    "MICHELE 24 J 24",
    "Michele Cliente",
    "Michele Devendo Pix",
    "Michelle 4 F 26 Roriz",
    "Michelle Nascimento",
    "Micro Make",
    "Miguel Freitas 31DP",
    "Mikaelly",
    "Milton",
    "Mineiro Motoboy",
    "Mineiro Motoboy",
    "Miney Souza",
    "Minha Fã Qd14 5 12",
    "Mm",
    "Moisés Cliente",
    "Mônica 05 i 44 Entre I E J",
    "Moura Policial",
    "Moysés",
    "Mulher Do 9",
    "Mulher Do Adriano",
    "Mulher Do Yuri",
    "Murillo Adeodato",
    "N",
    "N",
    "Nagyla Cruz Cruz",
    "Naiara 21 I 08",
    "Nair Clínica Dos Pés",
    "Nana",
    "Natacha 3 H 40, Loja Moda Casa",
    "Naynhene Leite",
    "Neide 14. 6. 20",
    "Neide 14.6.12 B3",
    "Neide Salazar",
    "Neidy Av. Gomes Rabelo 35 Casa 07",
    "Nelio Cliente",
    "Neusa",
    "Nice Cliente",
    "Nilda Silva",
    "Nn",
    "noelly 19 A 29 Skina 29",
    "Nubia 13.02.05 B3",
    "Osmar",
    "Pag Seguro",
    "Paiza 18 A 13 B4",
    "Paolla Emanuelle Óticas Carol",
    "Patricia",
    "Patricia Cliente",
    "Patrícia, Q8, Rua C, Casa 16 Vila Vicentina",
    "Paula Diego",
    "Paula Heleres Exato Laboratório",
    "Paulo 23 F 10",
    "Paulo 31°DP",
    "Paulo Cliente",
    "PAULO HENRIQUE",
    "Paulo Henrique",
    "Paulo Samir",
    "Pedro Paulo",
    "Pedro Ribeiro Ribeiro",
    "Pedro Verdura Chácara 57",
    "Perninha 2 C 19 Fundos",
    "Philip Colégio Aprovação",
    "Placa Solar Josimar",
    "PLASTICK ATACADISTA",
    "Policia",
    "Prima Do Yuri",
    "Priscila  13.08. 16 buritis 3",
    "Priscila Cdc",
    "Qd E, Conj E2, Casa 09 Marcos",
    "Quadra 4 conj D cs 03 vila buritis Entre o C e o D",
    "R2 Construtora",
    "Raça Embalagens",
    "Rafael Motoboy",
    "Rafaela",
    "Raiane Cliente",
    "Raimundo Campos 21 J 06",
    "Raissa Kedma Kids",
    "Ramerson 25 H 30",
    "Raony Cliente",
    "Rapaz D Uber",
    "Rapha",
    "Raphael 21A- C - 08",
    "Raquel",
    "Raquel KRS Espaço Da Blz Quadra 3. J .20",
    "Raquel Quadra 07 B conjunto C casa 9B próximo ao terminal do arapoangas",
    "Rayane 06 A 48 Apt 02 Roriz",
    "Rebeca 19 De Agosto,98,Cs3",
    "Rebeca C. Pra quadra 10 conjunto M casa 11 Buritis II",
    "Rebeca CEF 02 DO ARAPONGAS",
    "Regina 11. 02. 02 B3",
    "Regina KEDMA Kids",
    "REGINALDO Cliente",
    "REI DAVI Marcenaria",
    "Renan 3 H 18",
    "Renata",
    "Representante Comercial Vivo Móveis e Fixo.",
    "Reynan Wanderson",
    "Ricardo 3 F 40",
    "Ricardo Cliente",
    "Ricardo Clientee",
    "Ricardo Tolentino",
    "Robelia Salão Dinolene",
    "Roberto Mercado Andrade",
    "Roberto Mercado Andrade",
    "Robson Fórum",
    "Rodrigo Cliente",
    "Rodrigo Freire Cliente",
    "Rodrigo Like Internet",
    "Rodrigo Lima",
    "Rodrigo Qd A 17 Arapoanga Rodrigão)",
    "Roger Peixoto Cliente",
    "Rogério 19 F 18 B4",
    "Rogério Pereira",
    "Rômulo Carroceiro",
    "RONALY Rua 02 De Abril 75- 16 Recepção Studio La Fit",
    "Ronanzin Barbearia",
    "Roni 24 M 8",
    "Rosana",
    "Rosângela Guedes Cliente",
    "Rose Dutra",
    "Rosimeire Cliente",
    "Rosy Cabeleireira",
    "Rubilar 21 A 16 B4",
    "Ruby bronze 2 A 24",
    "Ruy  22A. D .02",
    "Salazar Cliente",
    "samuel Verdurão Do Pedro",
    "Samuel...",
    "santoslauda4",
    "sergio Cliente",
    "Sérgio Maurício Cliente",
    "Sgt Cristiano 14Bpm",
    "Shirley Maia",
    "Sidinei Geraldo Lopes",
    "Sidney 001",
    "sidneygomespalestra",
    "Sildesson 25 G 10",
    "Silvana 25 H 03",
    "Simone Vizinha",
    "Sineide 5 J 27 Roriz",
    "Sinomar",
    "Sissa Cliente",
    "Sizelma Gomes",
    "solange Andrade",
    "Sonia Cliente",
    "Stéfane Ribeiro",
    "Stefani 24 D 29 Apt 03",
    "Stefany Salão",
    "Sueli",
    "Taay Cliente",
    "Tânia Maria Guimarães",
    "Tata 15 F 20c Loja 01 Arapoanga",
    "Tatiana Rede Odonto Acima Da Casa Brasileira",
    "Tatiara",
    "Tay",
    "Teresa 23 F 26",
    "Tereza Chácara 68",
    "Th Games",
    "Thainá Mercado Andrade",
    "THAIS 3 A 20 Salão Da Zeny",
    "Thaise 4 G 6",
    "Thamys Gonçalves",
    "Thiago Cliente",
    "Thiago Polo",
    "Thiego 11. 2 . 2 B3",
    "Thulio",
    "Tiago Cliente",
    "Tio Do Yuri",
    "Tio Léo",
    "Ty",
    "Uivison",
    "Valdemiro Cliente",
    "valdenei cliente",
    "Valdir Cliente",
    "Valéria Qrk 7- Casa 03",
    "Valter",
    "Vanailda 01 G 48 Roriz Império Bebidas",
    "Vanderson Endereço entre quadra 1/2 loja 02 jardim Roriz Depósito de bebidas a saideira",
    "Vanilde",
    "Verlei 10 M 18",
    "Verônica Dourado Studio Hair",
    "Verônica qd 4 E conj B lote 11 arapongas",
    "Vicente 03 I 38",
    "Victor Cliente",
    "Victor Garcia AGM Pneus",
    "Vilma Cliente",
    "Vinicius",
    "Vinícius",
    "Vitor",
    "Vitor Rua D, Q 11, Casa 22",
    "Vitória Embalagens",
    "Vitória Embalagens 2",
    "Viviane",
    "Viviane Silva Cliente",
    "Wanderley Cliente",
    "Wanderson 24 E 05",
    "Wanderson 25 H 41",
    "Wanderson Embalagem",
    "Welington 16. 7. 10",
    "Wender",
    "Whueber Chácara 67 Corrego Do Atoleiro",
    "Wilian Cliente Centrinho",
    "William Paiva",
    "Wilma 2 F 47 Fundos",
    "Wilson Ginásio De Esportes",
    "Wndel Samuel",
    "Wz Construções Civil",
    "Ygor Gabriel",
    "Yure",
    "Yy",
    "Zeny 03 A 20",
    "ZionPublicidade",
    "Zozo Fornecedor De Frutas E Verduras",
    "Zumira",
]
